schemas:
  bind: &bind
    - lib
    - test
    - server.js
    - bin
  coverage: &disable-coverage
    enabled: false
  envs:
    local-service: &local-service-env
      service_port: 3000
      service_host_name: localhost
      domapic_path: .test
      service_extra_options: --relayGpio1=2 --sensorGpio=17 --relayGpio2=3 --logLevel=debug
    docker-service: &docker-service-env
      service_port: 3000
      service_host_name: module-container
      domapic_path: .shared
      service_extra_options: --relayGpio1=2 --sensorGpio=17 --relayGpio2=3 --logLevel=debug
  clean: &clean
    local:
      command: test/functional/commands/local-clean.sh
    docker:
      container: service-container
      command: test/functional/commands/clean.sh
      down-volumes: true
  services:
    local: &local-service
      command: test/functional/commands/start-module.sh
      env: *local-service-env
    docker: &docker-service
      container: module-container
      command: test/functional/commands/start-module.sh
      env: *docker-service-env
    local-cli: &local-service-cli
      <<: *local-service
      command: test/functional/commands/start-module-cli.sh
    docker-cli: &docker-service-cli
      <<: *docker-service
      command: test/functional/commands/start-module-cli.sh
  test: &functional-test
    local:
      wait-on: tcp:localhost:3000
      env: *local-service-env
    docker:
      container: test-container
      wait-on: tcp:module-container:3000
      env: *docker-service-env
docker-images:
  - name: node-image
    from: node:8.11.1
    expose:
      - 3000
    add:
      - package.json
      - npm-shrinkwrap.json
    install: test/functional/commands/install.sh
docker-containers:
  - name: module-container
    build: node-image
    bind: *bind
  - name: test-container
    build: node-image
    bind: *bind
suites:
  unit:
    - name: unit 
      test:
        specs: test/unit
      coverage:
        config:
          dir: .coverage
  functional:
    - name: api-and-config
      describe: should init the switch with provided configuration, and api should work as expected
      before: *clean
      services:
        - name: module
          abort-on-error: true
          local: *local-service
          docker: *docker-service
      test:
        <<: *functional-test
        specs:
          - test/functional/specs/api.specs.js
          - test/functional/specs/config.specs.js
      coverage: *disable-coverage
    - name: api-and-config-reverse
      describe: should init the switch with provided configuration, and api should work as expected
      before: *clean
      services:
        - name: module
          abort-on-error: true
          local:
            <<: *local-service
            env:
              <<: *local-service-env
              service_extra_options: --relayGpio1=5 --sensorGpio=2 --ways=3 --debounce=3000 --reverse=true --logLevel=debug
          docker:
            <<: *docker-service
            env:
              <<: *docker-service-env
              service_extra_options: --relayGpio1=5 --sensorGpio=2 --ways=3 --debounce=3000 --reverse=true --logLevel=debug
      test:
        <<: *functional-test
        specs:
          - test/functional/specs/api-reverse.specs.js
          - test/functional/specs/config-reverse.specs.js
      coverage: *disable-coverage
    - name: api-and-config-cli
      describe: should init the switch with provided configuration, and api should work as expected when started using cli
      before: *clean
      services:
        - name: module
          abort-on-error: true
          local: *local-service-cli
          docker: *docker-service-cli
      test:
        <<: *functional-test
        specs:
          - test/functional/specs/api.specs.js
          - test/functional/specs/config.specs.js
      coverage: *disable-coverage
